# Generated by Django 4.2.7 on 2023-11-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='sueldo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicio',
            name='costo',
            field=models.IntegerField(default=0),
        ),
    ]
