# Generated by Django 4.2.7 on 2023-11-17 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_empleado_sueldo_servicio_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
